<a href="https://colab.research.google.com/github/iabhinavtiwari247/Data-Science-Assignment---Google-Collab/blob/main/Abhinav_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [27]:
#data science assignment

In [28]:
#ANSWER 1
# Pandas DataFrame Assignment
# Name: Abhinav
# Subject: Data Science / Python
import pandas as pd
import numpy as np
Series1 = pd.Series([100,200,300,400,500], index=['A','B','C','D','E'])
Series2 = Series1 * 2
print (Series2)

A     200
B     400
C     600
D     800
E    1000
dtype: int64

In [29]:
#ANSWER 2
#a. False (Series size is immutable)
#b. True (DataFrame values are mutable)

In [30]:
#answer 3
import pandas as pd
Series1 = pd.Series([700,700,700,700,700], index=[200,201,202,203,204])
print(Series1)

200    700
201    700
202    700
203    700
204    700
dtype: int64

In [31]:
#answer 4
import pandas as pd
sIP = pd.Series([95, 89, 92, 95],
                index=['IP', 'Physics', 'Chemistry', 'Math'])
print(sIP)

print(sIP['IP'])
sIP + 10

IP           95
Physics      89
Chemistry    92
Math         95
dtype: int64
95

IP           105
Physics       99
Chemistry    102
Math         105
dtype: int64

In [32]:
#answer 5
import pandas as pd
SQTR = pd.Series([50000,65890,56780,89000,77900],
                 index=['QTR1','QTR2','QTR3','QTR4','QTR5'])
print(SQTR)

QTR1    50000
QTR2    65890
QTR3    56780
QTR4    89000
QTR5    77900
dtype: int64

In [33]:
#answer 6
import pandas as pd
S1 = pd.Series(data=[31, 41, 51])
S1
print(S1 > 40)
print(S1[S1 > 40])

0    False
1     True
2     True
dtype: bool
1    41
2    51
dtype: int64

In [34]:
#answer 7
import pandas as pd
S1 = pd.Series([39, 41, 42, 44], index=['A', 'B', 'C', 'D'])
S2 = pd.Series([10, 10, 10], index=['A', 'B', 'F'])

print(S1)
print(S2)
S1[:2] * 100
print(S1 * S2)
S2[::-1] * 10

A    39
B    41
C    42
D    44
dtype: int64
A    10
B    10
F    10
dtype: int64
A    390.0
B    410.0
C      NaN
D      NaN
F      NaN
dtype: float64

F    100
B    100
A    100
dtype: int64

In [35]:
#answer 8
import pandas as pd
S1 = pd.Series([10, 20, 30, 40], index=['A', 'B', 'C', 'D'])
S2 = pd.Series([5, 4, 6, 8], index=['A', 'B', 'C', 'D'])

print(S1)
print(S2)
S1 * S2

A    10
B    20
C    30
D    40
dtype: int64
A    5
B    4
C    6
D    8
dtype: int64

A     50
B     80
C    180
D    320
dtype: int64

In [36]:
#Answer 9
import pandas as pd
Subject = pd.Series([75,78,82,86],
                    index=['ENGLISH','HINDI','MATHS','SCIENCE'])
print(Subject)

ENGLISH    75
HINDI      78
MATHS      82
SCIENCE    86
dtype: int64

In [37]:
#answer 10
import pandas as pd
company = pd.Series([350, 200, 800, 150],
                    index=['TCS', 'Reliance', 'L&T', 'Wipro'])

print(company)
#Display name of companies having profit > 250
company[company > 250].index
company.name = 'Profit'
company

TCS         350
Reliance    200
L&T         800
Wipro       150
dtype: int64

TCS         350
Reliance    200
L&T         800
Wipro       150
Name: Profit, dtype: int64

In [38]:
#answer 11
import pandas as pd
a = [10, 20, 25, 50]          # Python list
b = pd.Series([10, 20, 25, 50])  # Pandas Series
print(a * 2)
print(b * 2)

[10, 20, 25, 50, 10, 20, 25, 50]
0     20
1     40
2     50
3    100
dtype: int64

In [39]:
#answer 12
# (b) print(Sample.tail(3))

In [40]:
#answer 13
import pandas as pd
s = pd.Series(6, index=range(0, 5))
s

0    6
1    6
2    6
3    6
4    6
dtype: int64

In [41]:
#answer 14
import pandas as pd
s1 = pd.Series([10, 20, 30, 4, 8, 7],
               index=[1, 3, 5, 9, 11, 13])

print(s1)
print(s1[3:6])

1     10
3     20
5     30
9      4
11     8
13     7
dtype: int64
9     4
11    8
13    7
dtype: int64

In [42]:
#answer 15
import pandas as pd
import numpy as np
s = pd.Series(np.arange(10, 50, 10))
print(s)
print(s.ndim)
print(s.shape)
print(len(s))

0    10
1    20
2    30
3    40
dtype: int64
1
(4,)
4

In [43]:
#answer 16
import pandas as pd
import numpy as np
random_series = pd.Series(np.random.randint(10, 21, 10))
random_series

0    15
1    14
2    20
3    12
4    19
5    16
6    15
7    13
8    10
9    14
dtype: int64

In [44]:
#answer 17
import pandas as pd
import numpy as np
s = pd.Series([4.0, 5.0, 7.0, np.nan, 1.0, 10.0])
print(s)
print(s + 1)
s.fillna(0)

0     4.0
1     5.0
2     7.0
3     NaN
4     1.0
5    10.0
dtype: float64
0     5.0
1     6.0
2     8.0
3     NaN
4     2.0
5    11.0
dtype: float64

0     4.0
1     5.0
2     7.0
3     0.0
4     1.0
5    10.0
dtype: float64

In [45]:
#answer 18
data = {'one': 'a', 'two': 'b', 'three': 'c'}
s = pd.Series(data)

print(s)
print(s.size)

one      a
two      b
three    c
dtype: object
3

In [46]:
#answer 19
S1 = pd.Series([2, 4, 6, 8])
S1

0    2
1    4
2    6
3    8
dtype: int64

In [47]:
#answer 20
s2 = pd.Series(["i", "am", "a", "student"])
print(s2)

0          i
1         am
2          a
3    student
dtype: object

In [48]:
# answer 21 // dataframe employee
import pandas as pd
Employee = pd.DataFrame({
    'Name': ['Atul','Raj','Darpan','Anmol','Piyush'],
    'Age': [25,30,23,22,32],
    'Designation': ['Manager','Clerk','Analyst','Clerk','Manager'],
    'Salary': [56000,25000,35000,28000,58000],
    'Bonus': [15000,7000,9000,13000,12000]
}, index=['E101','E102','E103','E104','E105'])

print(Employee)

Employee.loc['E106'] = ['GEET', 0, 'Analyst', 70000, 15000]
print(Employee)

Employee['Shift'] = 'Morning'


Employee[Employee['Age'] == Employee['Age'].min()]

Employee[Employee['Designation'] == 'Clerk']
Employee['Bonus'].mean()
Employee['Salary'].sum()
Employee['City'] = ['Janak Puri','Tilak Nagar','Shiv Nagar',
                    'Vikas Puri','Janak Puri','Tilak Nagar']
Employee.drop(['E103','E105'], inplace=True)

Employee.rename(columns={'Bonus':'Incentive'}, inplace=True)

        Name  Age Designation  Salary  Bonus
E101    Atul   25     Manager   56000  15000
E102     Raj   30       Clerk   25000   7000
E103  Darpan   23     Analyst   35000   9000
E104   Anmol   22       Clerk   28000  13000
E105  Piyush   32     Manager   58000  12000
        Name  Age Designation  Salary  Bonus
E101    Atul   25     Manager   56000  15000
E102     Raj   30       Clerk   25000   7000
E103  Darpan   23     Analyst   35000   9000
E104   Anmol   22       Clerk   28000  13000
E105  Piyush   32     Manager   58000  12000
E106    GEET    0     Analyst   70000  15000

In [49]:
# answer 21 // dataframe employee
import pandas as pd
Employee = pd.DataFrame({
    'Name': ['Atul','Raj','Darpan','Anmol','Piyush'],
    'Age': [25,30,23,22,32],
    'Designation': ['Manager','Clerk','Analyst','Clerk','Manager'],
    'Salary': [56000,25000,35000,28000,58000],
    'Bonus': [15000,7000,9000,13000,12000]
}, index=['E101','E102','E103','E104','E105'])

print(Employee)

Employee.loc['E106'] = ['GEET', 0, 'Analyst', 70000, 15000]
print(Employee)

Employee['Shift'] = 'Morning'


Employee[Employee['Age'] == Employee['Age'].min()]

Employee[Employee['Designation'] == 'Clerk']
Employee['Bonus'].mean()
Employee['Salary'].sum()
Employee['City'] = ['Janak Puri','Tilak Nagar','Shiv Nagar',
                    'Vikas Puri','Janak Puri','Tilak Nagar']
Employee.drop(['E103','E105'], inplace=True)

Employee.rename(columns={'Bonus':'Incentive'}, inplace=True)

        Name  Age Designation  Salary  Bonus
E101    Atul   25     Manager   56000  15000
E102     Raj   30       Clerk   25000   7000
E103  Darpan   23     Analyst   35000   9000
E104   Anmol   22       Clerk   28000  13000
E105  Piyush   32     Manager   58000  12000
        Name  Age Designation  Salary  Bonus
E101    Atul   25     Manager   56000  15000
E102     Raj   30       Clerk   25000   7000
E103  Darpan   23     Analyst   35000   9000
E104   Anmol   22       Clerk   28000  13000
E105  Piyush   32     Manager   58000  12000
E106    GEET    0     Analyst   70000  15000

In [50]:
# answer 21 // dataframe employee
import pandas as pd
Employee = pd.DataFrame({
    'Name': ['Atul','Raj','Darpan','Anmol','Piyush'],
    'Age': [25,30,23,22,32],
    'Designation': ['Manager','Clerk','Analyst','Clerk','Manager'],
    'Salary': [56000,25000,35000,28000,58000],
    'Bonus': [15000,7000,9000,13000,12000]
}, index=['E101','E102','E103','E104','E105'])

print(Employee)

Employee.loc['E106'] = ['GEET', 0, 'Analyst', 70000, 15000]
print(Employee)

Employee['Shift'] = 'Morning'
print(Employee)

Employee[Employee['Age'] == Employee['Age'].min()]


Employee[Employee['Designation'] == 'Clerk']
Employee['Bonus'].mean()
Employee['Salary'].sum()
Employee['City'] = ['Janak Puri','Tilak Nagar','Shiv Nagar',
                    'Vikas Puri','Janak Puri','Tilak Nagar']
Employee.drop(['E103','E105'], inplace=True)

Employee.rename(columns={'Bonus':'Incentive'}, inplace=True)

        Name  Age Designation  Salary  Bonus
E101    Atul   25     Manager   56000  15000
E102     Raj   30       Clerk   25000   7000
E103  Darpan   23     Analyst   35000   9000
E104   Anmol   22       Clerk   28000  13000
E105  Piyush   32     Manager   58000  12000
        Name  Age Designation  Salary  Bonus
E101    Atul   25     Manager   56000  15000
E102     Raj   30       Clerk   25000   7000
E103  Darpan   23     Analyst   35000   9000
E104   Anmol   22       Clerk   28000  13000
E105  Piyush   32     Manager   58000  12000
E106    GEET    0     Analyst   70000  15000
        Name  Age Designation  Salary  Bonus    Shift
E101    Atul   25     Manager   56000  15000  Morning
E102     Raj   30       Clerk   25000   7000  Morning
E103  Darpan   23     Analyst   35000   9000  Morning
E104   Anmol   22       Clerk   28000  13000  Morning
E105  Piyush   32     Manager   58000  12000  Morning
E106    GEET    0     Analyst   70000  15000  Morning

In [51]:
# answer 21 // dataframe employee
import pandas as pd

# Create Employee DataFrame
Employee = pd.DataFrame({
    'Name': ['Atul','Raj','Darpan','Anmol','Piyush'],
    'Age': [25,30,23,22,32],
    'Designation': ['Manager','Clerk','Analyst','Clerk','Manager'],
    'Salary': [56000,25000,35000,28000,58000],
    'Bonus': [15000,7000,9000,13000,12000]
}, index=['E101','E102','E103','E104','E105'])

print("Initial Employee DataFrame:")
print(Employee)

# a) Add a new row
Employee.loc['E106'] = ['GEET', 0, 'Analyst', 70000, 15000]
print("\nAfter adding new employee:")
print(Employee)

# b) Add column Shift
Employee['Shift'] = 'Morning'
print("\nAfter adding Shift column:")
print(Employee)

# c) Youngest employee
print("\nYoungest employee:")
print(Employee[Employee['Age'] == Employee['Age'].min()])

# d) Employees with Designation Clerk
print("\nEmployees with designation Clerk:")
print(Employee[Employee['Designation'] == 'Clerk'])

# e) Average Bonus
print("\nAverage Bonus:")
print(Employee['Bonus'].mean())

# f) Total Salary
print("\nTotal Salary:")
print(Employee['Salary'].sum())

# g) Add City column
Employee['City'] = [
    'Janak Puri','Tilak Nagar','Shiv Nagar',
    'Vikas Puri','Janak Puri','Tilak Nagar'
]
print("\nAfter adding City column:")
print(Employee)

# h) Delete employees E103 and E105
Employee.drop(['E103','E105'], inplace=True)
print("\nAfter deleting employees E103 and E105:")
print(Employee)

# i) Rename Bonus column to Incentive
Employee.rename(columns={'Bonus':'Incentive'}, inplace=True)
print("\nAfter renaming Bonus to Incentive:")
print(Employee)

Initial Employee DataFrame:
        Name  Age Designation  Salary  Bonus
E101    Atul   25     Manager   56000  15000
E102     Raj   30       Clerk   25000   7000
E103  Darpan   23     Analyst   35000   9000
E104   Anmol   22       Clerk   28000  13000
E105  Piyush   32     Manager   58000  12000

After adding new employee:
        Name  Age Designation  Salary  Bonus
E101    Atul   25     Manager   56000  15000
E102     Raj   30       Clerk   25000   7000
E103  Darpan   23     Analyst   35000   9000
E104   Anmol   22       Clerk   28000  13000
E105  Piyush   32     Manager   58000  12000
E106    GEET    0     Analyst   70000  15000

After adding Shift column:
        Name  Age Designation  Salary  Bonus    Shift
E101    Atul   25     Manager   56000  15000  Morning
E102     Raj   30       Clerk   25000   7000  Morning
E103  Darpan   23     Analyst   35000   9000  Morning
E104   Anmol   22       Clerk   28000  13000  Morning
E105  Piyush   32     Manager   58000  12000  Morning
E106    GEET    0     Analyst   70000  15000  Morning

Youngest employee:
      Name  Age Designation  Salary  Bonus    Shift
E106  GEET    0     Analyst   70000  15000  Morning

Employees with designation Clerk:
       Name  Age Designation  Salary  Bonus    Shift
E102    Raj   30       Clerk   25000   7000  Morning
E104  Anmol   22       Clerk   28000  13000  Morning

Average Bonus:
11833.333333333334

Total Salary:
272000

After adding City column:
        Name  Age Designation  Salary  Bonus    Shift         City
E101    Atul   25     Manager   56000  15000  Morning   Janak Puri
E102     Raj   30       Clerk   25000   7000  Morning  Tilak Nagar
E103  Darpan   23     Analyst   35000   9000  Morning   Shiv Nagar
E104   Anmol   22       Clerk   28000  13000  Morning   Vikas Puri
E105  Piyush   32     Manager   58000  12000  Morning   Janak Puri
E106    GEET    0     Analyst   70000  15000  Morning  Tilak Nagar

After deleting employees E103 and E105:
       Name  Age Designation  Salary  Bonus    Shift         City
E101   Atul   25     Manager   56000  15000  Morning   Janak Puri
E102    Raj   30       Clerk   25000   7000  Morning  Tilak Nagar
E104  Anmol   22       Clerk   28000  13000  Morning   Vikas Puri
E106   GEET    0     Analyst   70000  15000  Morning  Tilak Nagar

After renaming Bonus to Incentive:
       Name  Age Designation  Salary  Incentive    Shift         City
E101   Atul   25     Manager   56000      15000  Morning   Janak Puri
E102    Raj   30       Clerk   25000       7000  Morning  Tilak Nagar
E104  Anmol   22       Clerk   28000      13000  Morning   Vikas Puri
E106   GEET    0     Analyst   70000      15000  Morning  Tilak Nagar

In [52]:
#ANSWER 22
import pandas as pd
import numpy as np

# =======================
# PART 1 : Items DataFrame
# =======================

# Step 0: Create the DataFrame
data = pd.DataFrame({
    'Count': [15, 20, 25, 35],
    'Price': [250, 200, 600, 900]
}, index=['Pencil', 'Pen', 'Eraser', 'Scale'])

print("Initial DataFrame:")
print(data)

# a) Change the Eraser count to 15
data.loc['Eraser', 'Count'] = 15
print("\nAfter changing Eraser count to 15:")
print(data)

# b) Rename index “Scale” as “Wooden Scale”
data.rename(index={'Scale': 'Wooden Scale'}, inplace=True)
print("\nAfter renaming Scale to Wooden Scale:")
print(data)

# c) Change all row labels
data.index = ['Product 1', 'Product 2', 'Product 3', 'Product 4']
print("\nAfter changing all row labels:")
print(data)

# d) Change column names to “Discount”, “Total”
data.columns = ['Discount', 'Total']
print("\nAfter changing column names:")
print(data)

# e) Add new row “Product 5” with values 10 and 100
data.loc['Product 5'] = [10, 100]
print("\nAfter adding Product 5:")
print(data)

# f) Create new DataFrame “Products” without column “Total”
Products = data.drop(columns=['Total'])
print("\nNew DataFrame Products (without Total column):")
print(Products)


# ==================================
# PART 2 : Agricultural Production DF
# ==================================

# Step 0: Create the DataFrame
df = pd.DataFrame({
    'Fruits': [44, 11950, 7152, 140169, 7830, 113],
    'Pulses': [23, 818, 33, 3184, 931, 1],
    'Rice': [814, 1930, 11586, 13574, 7452, 2604],
    'Wheat': [5, 2737, 16440, 30056, np.nan, np.nan]
}, index=['Tripura', 'Gujrat', 'Punjab', 'UP', 'AP', 'Kerala'])

print("\nAgricultural Production DataFrame:")
print(df)

# a) Total production for each state
print("\nTotal production for each state:")
print(df.sum(axis=1))

# b) Total production for each item type
print("\nTotal production for each item type:")
print(df.sum())

# c) How many states produce Wheat?
print("\nNumber of states producing Wheat:")
print(df['Wheat'].count())

Initial DataFrame:
        Count  Price
Pencil     15    250
Pen        20    200
Eraser     25    600
Scale      35    900

After changing Eraser count to 15:
        Count  Price
Pencil     15    250
Pen        20    200
Eraser     15    600
Scale      35    900

After renaming Scale to Wooden Scale:
              Count  Price
Pencil           15    250
Pen              20    200
Eraser           15    600
Wooden Scale     35    900

After changing all row labels:
           Count  Price
Product 1     15    250
Product 2     20    200
Product 3     15    600
Product 4     35    900

After changing column names:
           Discount  Total
Product 1        15    250
Product 2        20    200
Product 3        15    600
Product 4        35    900

After adding Product 5:
           Discount  Total
Product 1        15    250
Product 2        20    200
Product 3        15    600
Product 4        35    900
Product 5        10    100

New DataFrame Products (without Total column):
           Discount
Product 1        15
Product 2        20
Product 3        15
Product 4        35
Product 5        10

Agricultural Production DataFrame:
         Fruits  Pulses   Rice    Wheat
Tripura      44      23    814      5.0
Gujrat    11950     818   1930   2737.0
Punjab     7152      33  11586  16440.0
UP       140169    3184  13574  30056.0
AP         7830     931   7452      NaN
Kerala      113       1   2604      NaN

Total production for each state:
Tripura       886.0
Gujrat      17435.0
Punjab      35211.0
UP         186983.0
AP          16213.0
Kerala       2718.0
dtype: float64

Total production for each item type:
Fruits    167258.0
Pulses      4990.0
Rice       37960.0
Wheat      49238.0
dtype: float64

Number of states producing Wheat:
4